### ISSUE TITLE
[Suggestion] Multiple Semesters

### ISSUE THREAD

**Issue by Xander04** [s3943811/PlanMyTimetable#32]
Hi,
Already discussed this on Reddit but I thought I'd make an official request. The ability to be able to select multiple semesters would be great for us who have subjects in a Flex semester.

Thanks!
Xander

**Comment by s3943811** [comment]
Hey! Thanks for opening an issue. Just gonna repeat what I said on reddit so I can remember to complete it: 
> I will consider updating the browser extensions to let you choose the semester and add other classes so you can add classes from flex semesters.

Currently, I'm envisioning this as an opt in feature where you select the semester first, then a checkbox to select other classes... does this meet with your requirements for multiple semesters?

**Comment by Xander04** [comment]
Sounds great!

**Comment by s3943811** [comment]
Hey, thanks for being patient with this. I have just submitted an update for the extension to select multiple semester's and classes individually.

It is now live on Firefox and waiting for review on Chrome (hopefully live soon). Here is a preview of it:

https://github.com/s3943811/PlanMyTimetable/assets/103098176/85936629-1b07-4c49-a97c-6e51d19321ea
