### ISSUE TITLE
Encountered multiple bugs - app unusable

### ISSUE THREAD

**Issue by Tonda39** [s3943811/PlanMyTimetable#35]
**Describe the bug**
1. Unable to switch between classes in "Classes" tab to edit them (the right side with class details never changes).
2. Unable to drag & drop classes to the timetable in the "Home" tab except the downmost one on the list.
3. After dragging & dropping a class to a time slot in the timetable I can then drag that time slot into a time slot of a different class. 

**To Reproduce**
[Link to a screen recording](https://youtu.be/uvQh8Wv9g60)

**Expected behavior**
1. After selecting a class from the left side list the class details should change on the right to reflect the selected class.
2. I should be able to drag & drop any class in any order to the timetable.
3. I shouldn't be able to drag an occupied time slot  into a timeslot of a different class.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: both Chrome and Firefox
 - Version Firefox - 122.0.1, Chrome - 121.0.6167.160 (Screen recording was taken when using chrome)

**Comment by s3943811** [comment]
Hey, sorry about this. I majorly overlooked something, this has now been fixed with #36 (be68564d2f0e2fc301f61e36271fa9fcf55cd3ca) please let me know if you have any further issues.
